export const countries = [
  { "label": "Afganistán" },
  { "label": "Albania" },
  { "label": "Alemania" },
  { "label": "Andorra" },
  { "label": "Angola" },
  { "label": "Antigua y Barbuda" },
  { "label": "Arabia Saudita" },
  { "label": "Argelia" },
  { "label": "Argentina" },
  { "label": "Armenia" },
  { "label": "Australia" },
  { "label": "Austria" },
  { "label": "Azerbaiyán" },
  { "label": "Bahamas" },
  { "label": "Bahréin" },
  { "label": "Bangladés" },
  { "label": "Barbados" },
  { "label": "Bélgica" },
  { "label": "Belice" },
  { "label": "Benín" },
  { "label": "Bielorrusia" },
  { "label": "Birmania" },
  { "label": "Bolivia" },
  { "label": "Bosnia y Herzegovina" },
  { "label": "Botsuana" },
  { "label": "Brasil" },
  { "label": "Brunéi" },
  { "label": "Bulgaria" },
  { "label": "Burkina Faso" },
  { "label": "Burundi" },
  { "label": "Cabo Verde" },
  { "label": "Camerún" },
  { "label": "Canadá" },
  { "label": "Chile" },
  { "label": "China" },
  { "label": "Colombia" },
  { "label": "Comoras" },
  { "label": "República del Congo" },
  { "label": "República Democrática del Congo" },
  { "label": "Costa Rica" },
  { "label": "Croacia" },
  { "label": "Cuba" },
  { "label": "Dinamarca" },
  { "label": "Dominica" },
  { "label": "República Dominicana" },
  { "label": "Ecuador" },
  { "label": "Egipto" },
  { "label": "El Salvador" },
  { "label": "Emiratos Árabes Unidos" },
  { "label": "Eslovenia" },
  { "label": "España" },
  { "label": "Estonia" },
  { "label": "Eswatini" },
  { "label": "Estados Unidos" },
  { "label": "Etiopía" },
  { "label": "Filipinas" },
  { "label": "Finlandia" },
  { "label": "Francia" },
  { "label": "Gabón" },
  { "label": "Gambia" },
  { "label": "Georgia" },
  { "label": "Ghana" },
  { "label": "Grecia" },
  { "label": "Granada" },
  { "label": "Guatemala" },
  { "label": "Guinea" },
  { "label": "Guinea-Bisáu" },
  { "label": "Guinea Ecuatorial" },
  { "label": "Haití" },
  { "label": "Holanda" },
  { "label": "Honduras" },
  { "label": "Hungría" },
  { "label": "India" },
  { "label": "Indonesia" },
  { "label": "Irán" },
  { "label": "Irak" },
  { "label": "Irlanda" },
  { "label": "Isla de Man" },
  { "label": "Islas Marshall" },
  { "label": "Islas Salomón" },
  { "label": "Italia" },
  { "label": "Jamaica" },
  { "label": "Japón" },
  { "label": "Jordania" },
  { "label": "Kazajistán" },
  { "label": "Kenia" },
  { "label": "Kirguistán" },
  { "label": "Kiribati" },
  { "label": "Kuwait" },
  { "label": "Laos" },
  { "label": "Lesoto" },
  { "label": "Letonia" },
  { "label": "Líbano" },
  { "label": "Liberia" },
  { "label": "Libia" },
  { "label": "Liechtenstein" },
  { "label": "Lituania" },
  { "label": "Luxemburgo" },
  { "label": "Madagascar" },
  { "label": "Malasia" },
  { "label": "Malaui" },
  { "label": "Maldivas" },
  { "label": "Malta" },
  { "label": "Marruecos" },
  { "label": "Mauricio" },
  { "label": "Mauritania" },
  { "label": "México" },
  { "label": "Moldavia" },
  { "label": "Mónaco" },
  { "label": "Mongolia" },
  { "label": "Mozambique" },
  { "label": "Namibia" },
  { "label": "Nauru" },
  { "label": "Nepal" },
  { "label": "Nicaragua" },
  { "label": "Níger" },
  { "label": "Nigeria" },
  { "label": "Noruega" },
  { "label": "Nueva Zelanda" },
  { "label": "Omán" },
  { "label": "Panamá" },
  { "label": "Paraguay" },
  { "label": "Perú" },
  { "label": "Polonia" },
  { "label": "Portugal" },
  { "label": "Reino Unido" },
  { "label": "República Checa" },
  { "label": "Rumanía" },
  { "label": "Rusia" },
  { "label": "Rwanda" },
  { "label": "Samoa" },
  { "label": "San Cristóbal y Nieves" },
  { "label": "San Marino" },
  { "label": "Santa Lucía" },
  { "label": "Santo Tomé y Príncipe" },
  { "label": "Senegal" },
  { "label": "Serbia" },
  { "label": "Seychelles" },
  { "label": "Sierra Leona" },
  { "label": "Singapur" },
  { "label": "Eslovaquia" },
  { "label": "Eslovenia" },
  { "label": "Somalia" },
  { "label": "Sudáfrica" },
  { "label": "Sudán" },
  { "label": "Sudán del Sur" },
  { "label": "Suecia" },
  { "label": "Suiza" },
  { "label": "Siria" },
  { "label": "Tailandia" },
  { "label": "Tanzania" },
  { "label": "Tayikistán" },
  { "label": "Timor Oriental" },
  { "label": "Togo" },
  { "label": "Tonga" },
  { "label": "Trinidad y Tobago" },
  { "label": "Túnez" },
  { "label": "Turkmenistán" },
  { "label": "Turquía" },
  { "label": "Tuvalu" },
  { "label": "Uganda" },
  { "label": "Ucrania" },
  { "label": "Uruguay" },
  { "label": "Uzbekistán" },
  { "label": "Vanuatu" },
  { "label": "Vaticano" },
  { "label": "Venezuela" },
  { "label": "Vietnam" },
  { "label": "Yemen" },
  { "label": "Zambia" },
  { "label": "Zimbabue" }
]